Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FishStore.Data;
using FishStore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using FishStore.Utility;

namespace FishStore.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }

        //GET
        public async Task<IActionResult> Index()
        {
            return View(await _db.Category.ToListAsync());
        }

        // GET FOR CREATE
        public IActionResult Create()
        {
            return View();
        }

        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Add(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        //GET - EDIT
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _db.Category.FindAsync(id); 
            if(category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //POST - EDIT
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                _db.Category.Update(category);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        //GET - DELETE
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        //POST - DELETE
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed (int id)
        {
            var category = await _db.Category.FindAsync(id);
            if(category == null)
            {
                return NotFound();
            }
            _db.Category.Remove(category);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //GET - DETAILS
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var category = await _db.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
    }
}

Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FishStore.Data;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using FishStore.Utility;

namespace FishStore.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUser.Where(u => u.Id != claim.Value).ToListAsync());
            
        }

        public async Task<IActionResult> Lock(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if(applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now.AddYears(100);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now;
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FishStore.Data;
using FishStore.Models;
using FishStore.Models.ViewModels;
using FishStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Stripe;

namespace FishStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public OrderDetailsCart detailCart { get; set; }

        public CartController(ApplicationDbContext db)
        {
            _db = db;
        }

        //INDEX - GET
        public async Task<IActionResult> Index()
        {


            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };

            detailCart.OrderHeader.OrderTotal = 0.0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ApplicationUser applicationUser = await _db.ApplicationUser.Where(c => c.Id == claim.Value).FirstOrDefaultAsync();
            if (claim != null)
            {
                var cnt = _db.ShoppingCart.Where(u => u.ApplicationUserId == claim.Value).ToList().Count;
                HttpContext.Session.SetInt32("ssCartCount", cnt);
            }

            var cart = _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value);
            if (cart != null)
            {
                detailCart.listCart = cart.ToList();
            }


            double weigth = 0.0;
            double volume = 0.0;

            foreach (var list in detailCart.listCart)
            {
                list.StoreItem = await _db.StoreItem.FirstOrDefaultAsync(m => m.Id == list.StoreItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.StoreItem.Price * list.Count);
                weigth += (list.StoreItem.Weight * list.Count);
                volume += (list.StoreItem.Volume * list.Count);
            }
            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;

            if (HttpContext.Session.GetString(SD.ssUserName) != null)
            {
                detailCart.OrderHeader.Name = HttpContext.Session.GetString(SD.ssUserName);
            }
            else
            {
                detailCart.OrderHeader.Name = applicationUser.Name;
            }
            if (HttpContext.Session.GetString(SD.ssUserAddress) != null)
            {
                detailCart.OrderHeader.Address = HttpContext.Session.GetString(SD.ssUserAddress);
            }
            else
            {
                detailCart.OrderHeader.Address = applicationUser.StreetAddress;
            }
            if (HttpContext.Session.GetString(SD.ssUserCity) != null)
            {
                detailCart.OrderHeader.City = HttpContext.Session.GetString(SD.ssUserCity);
            }
            else
            {
                detailCart.OrderHeader.City = applicationUser.City;
            }
            if (HttpContext.Session.GetString(SD.ssUserState) != null)
            {
                detailCart.OrderHeader.State = HttpContext.Session.GetString(SD.ssUserState);
            }
            else
            {
                detailCart.OrderHeader.State = applicationUser.State;
            }

            if (HttpContext.Session.GetString(SD.ssPostalCode) != null)
            {
                detailCart.OrderHeader.PostalCode = HttpContext.Session.GetString(SD.ssPostalCode);
                string[] precoPrazo = await SD.GetPriceAndTimePostalServiceAsync(detailCart.OrderHeader.PostalCode, weigth, volume);
                detailCart.OrderHeader.PostalPrice = Convert.ToDouble(precoPrazo[0]);
                detailCart.OrderHeader.PostalTime = Convert.ToDouble(precoPrazo[1]);
                detailCart.OrderHeader.OrderTotal += detailCart.OrderHeader.PostalPrice;
                HttpContext.Session.SetInt32("ssPostalPrice", Convert.ToInt32(detailCart.OrderHeader.PostalPrice * 100));
            }
            else
            {
                detailCart.OrderHeader.PostalCode = applicationUser.PostalCode;
                string[] precoPrazo = await SD.GetPriceAndTimePostalServiceAsync(detailCart.OrderHeader.PostalCode, weigth, volume);
                detailCart.OrderHeader.PostalPrice = Convert.ToDouble(precoPrazo[0]);
                detailCart.OrderHeader.PostalTime = Convert.ToDouble(precoPrazo[1]);
                detailCart.OrderHeader.OrderTotal += detailCart.OrderHeader.PostalPrice;
                HttpContext.Session.SetInt32("ssPostalPrice", Convert.ToInt32(detailCart.OrderHeader.PostalPrice * 100));
            }


            return View(detailCart);
        }

        //SUMMARY - GET
        public async Task<IActionResult> Summary()
        {

            detailCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };

            detailCart.OrderHeader.OrderTotal = 0.0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ApplicationUser applicationUser = await _db.ApplicationUser.Where(c => c.Id == claim.Value).FirstOrDefaultAsync();
            if (claim != null)
            {
                var cnt = _db.ShoppingCart.Where(u => u.ApplicationUserId == claim.Value).ToList().Count;
                HttpContext.Session.SetInt32("ssCartCount", cnt);
            }

            var cart = _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value);
            if (cart != null)
            {
                detailCart.listCart = cart.ToList();
            }

            double weigth = 0.0;
            double volume = 0.0;

            foreach (var list in detailCart.listCart)
            {
                list.StoreItem = await _db.StoreItem.FirstOrDefaultAsync(m => m.Id == list.StoreItemId);
                detailCart.OrderHeader.OrderTotal = detailCart.OrderHeader.OrderTotal + (list.StoreItem.Price * list.Count);
                weigth += (list.StoreItem.Weight * list.Count);
                volume += (list.StoreItem.Volume * list.Count);
            }
            detailCart.OrderHeader.OrderTotalOriginal = detailCart.OrderHeader.OrderTotal;

            if (HttpContext.Session.GetString(SD.ssUserName) != null)
            {
                detailCart.OrderHeader.Name = HttpContext.Session.GetString(SD.ssUserName);
            }
            else
            {
                detailCart.OrderHeader.Name = applicationUser.Name;
            }
            if (HttpContext.Session.GetString(SD.ssUserAddress) != null)
            {
                detailCart.OrderHeader.Address = HttpContext.Session.GetString(SD.ssUserAddress);
            }
            else
            {
                detailCart.OrderHeader.Address = applicationUser.StreetAddress;
            }
            if (HttpContext.Session.GetString(SD.ssUserCity) != null)
            {
                detailCart.OrderHeader.City = HttpContext.Session.GetString(SD.ssUserCity);
            }
            else
            {
                detailCart.OrderHeader.City = applicationUser.City;
            }
            if (HttpContext.Session.GetString(SD.ssUserState) != null)
            {
                detailCart.OrderHeader.State = HttpContext.Session.GetString(SD.ssUserState);
            }
            else
            {
                detailCart.OrderHeader.State = applicationUser.State;
            }

            if (HttpContext.Session.GetString(SD.ssPostalCode) != null)
            {
                detailCart.OrderHeader.PostalCode = HttpContext.Session.GetString(SD.ssPostalCode);
                string[] precoPrazo = await SD.GetPriceAndTimePostalServiceAsync(detailCart.OrderHeader.PostalCode, weigth, volume);
                detailCart.OrderHeader.PostalPrice = Convert.ToDouble(precoPrazo[0]);
                detailCart.OrderHeader.PostalTime = Convert.ToDouble(precoPrazo[1]);
                detailCart.OrderHeader.OrderTotal += detailCart.OrderHeader.PostalPrice;
                HttpContext.Session.SetInt32("ssPostalPrice", Convert.ToInt32(detailCart.OrderHeader.PostalPrice * 100));
            }
            else
            {
                detailCart.OrderHeader.PostalCode = applicationUser.PostalCode;
                string[] precoPrazo = await SD.GetPriceAndTimePostalServiceAsync(detailCart.OrderHeader.PostalCode, weigth, volume);
                detailCart.OrderHeader.PostalPrice = Convert.ToDouble(precoPrazo[0]);
                detailCart.OrderHeader.PostalTime = Convert.ToDouble(precoPrazo[1]);
                detailCart.OrderHeader.OrderTotal += detailCart.OrderHeader.PostalPrice;
                HttpContext.Session.SetInt32("ssPostalPrice", Convert.ToInt32(detailCart.OrderHeader.PostalPrice * 100));
            }

            return View(detailCart);
        }

        //SUMMARY - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(string stripeToken)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            detailCart.listCart = await _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value).ToListAsync();

            detailCart.OrderHeader.UserId = claim.Value;
            detailCart.OrderHeader.Status = SD.PaymentStatusPending;
            detailCart.OrderHeader.OrderDate = DateTime.Now;
            detailCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;

            var postalPrice = HttpContext.Session.GetInt32("ssPostalPrice");

Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Criar" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Voltar</a>
    </div>
</div>

Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i> &nbsp; Criar</a>
</p>

Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-Id="@Model" value="Excluir" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Voltar</a>
    </div>
</div>

Views/Shared/_DetailsAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <a class="btn btn-info form-control" asp-action="Edit" asp-route-Id="@Model">
            Editar
        </a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Voltar</a>
    </div>
</div>

Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-Id="@Model" value="Atualizar" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Voltar</a>
    </div>
</div>

Views/Shared/_IndividualOrderDetails.cshtml
@model FishStore.Models.ViewModels.OrderDetailsViewModel
@using FishStore.Utility
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<form asp-action="OrderPickUp" asp-controller="Order" asp-route-orderId="@Model.OrderHeader.Id" method="post">
    <div class="container row border rounded ml-1 p-3">
        <div class="col-lg-8 col-12" style="border-right:1px solid #bbb9b9">
            <br />
            <input type="hidden" asp-for="OrderHeader.Id" />
            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">Nome</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Name" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">Email</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">Data</label>
                </div>
                <div class="col-9">
                    <input value="@Model.OrderHeader.OrderDate.ToString("dd/MM/yyyy HH:mm:ss")" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">Endereço</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.Address" disabled class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">Cidade</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.City" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">Estado</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.State" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3">
                    <label class="font-weight-bold">CEP</label>
                </div>
                <div class="col-9">
                    <input asp-for="OrderHeader.PostalCode" disabled class="form-control" />
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-12">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">ID Pedido:</span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.Id</span>
            </h4>
            <ul class="list-group mb-3">
                @foreach (var details in Model.OrderDetails)
                {
                    <li class=" list-group-item d-flex justify-content-between">
                        <div>
                            <h6 class="my-0">@details.Name</h6>
                            <small class="text-muted">Quantidade: @details.Count</small>
                        </div>
                        <span class="text-muted">@(details.Count * details.Price)</span>
                    </li>
                }

                <li class=" list-group-item d-flex justify-content-between">
                    <div class="text-success">
                        <h6 class="my-0">Frete</h6>
                        <small>Sedex</small>
                    </div>
                    <span class="text-success">@Model.OrderHeader.PostalPrice</span>

                </li>
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <span class="text-info">Total (BRL)</span>
                    <strong class="text-info">@Model.OrderHeader.OrderTotal.ToString("C2")</strong>
                </li>

            </ul>
            @if (Model.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerUser)))
            {
                <button type="submit" class="btn btn-success form-control"><i class="far fa-thumbs-up"></i> Item Postado</button>
            }
            else
            {
                <button type="submit" disabled class="btn btn-info form-control">@Model.OrderHeader.Status</button>
            }
        </div>
    </div>
</form>

Views/Shared/_Layout.cshtml
@using FishStore.Utility
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>FakeFishStore</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.0.3/nouislider.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/MeuCss.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ca63af555e.js" crossorigin="anonymous"></script>
    <link rel="shortcut icon" href="~/images/favicon.ico" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md fixed-top navbar-toggleable-md m-0" style="background: rgba(0, 0, 0, 0.8)!important;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index"><img style="height:3rem" src="~/images/logo.png" alt="NavbarBrand" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="custom-toggler-icon">
                        <i class="fas fa-bars"></i>
                    </span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex flex-md-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown navbar-textu">
                                <a class="nav-link dropdown-toggle navbar-textu p-0" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    GERENCIAR CONTEÚDO
                                </a>
                                <div class="dropdown-menu" style="background: rgba(0, 0, 0, 0.8) !important;" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item navbar-textu" asp-action="Index" asp-controller="Category" asp-area="Admin">CATEGORIA</a>
                                    <a class="dropdown-item navbar-textu" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">SUBCATEGORIA</a>
                                    <a class="dropdown-item navbar-textu" asp-action="Index" asp-controller="StoreItem" asp-area="Admin">ITENS</a>
                                    <a class="dropdown-item navbar-textu" asp-action="Index" asp-controller="User" asp-area="Admin">USUÁRIOS</a>
                                </div>

                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link navbar-textu" asp-area="Customer" asp-controller="Home" asp-action="Products">PRODUTOS</a>
                        </li>
                        @if (User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item">
                                <a class="nav-link navbar-textu text-uppercase" asp-area="Customer" asp-controller="Order" asp-action="OrderHistory">Histórico de Pedidos</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown navbar-textu">
                                <a class="nav-link dropdown-toggle navbar-textu p-0" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    PEDIDOS
                                </a>
                                <div class="dropdown-menu" style="background: rgba(0, 0, 0, 0.8) !important;" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item navbar-textu text-uppercase" asp-action="ManageOrder" asp-controller="Order" asp-area="Customer">Gerenciar Pedidos</a>
                                    <a class="dropdown-item navbar-textu text-uppercase" asp-action="OrderPickup" asp-controller="Order" asp-area="Customer">Postar Pedidos</a>

                                </div>

                            </li>
                        }

                        @if ((HttpContextAccessor.HttpContext.Session.GetInt32("ssCartCount") != null) && (User.IsInRole(SD.CustomerEndUser) || User.IsInRole(SD.ManagerUser)))
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link navbar-textu">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32("ssCartCount");
                                    }
                                    <i class="fas fa-shopping-cart"></i> (@count)
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="p-0 m-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-light ">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    &copy; 2020 - FakeFishStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Política de Privacidade</a>
                </div>
                <div class="col-md-6">
                    Criado Por: Lucas Mourão Ferreira - lucas.mo.ferr@gmail.com
                </div>
            </div>
        </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/noUiSlider/14.0.3/nouislider.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<StoreItem>
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

@if (Model.Count() > 0)
{
    <div class="row">
        @foreach (var item in Model)
        {
            <div  class="card-deck col-sm-12 col-md-6 col-lg-3 @item.Category.Name.Replace(" ",string.Empty) @item.Name.Replace(" ", string.Empty).ToUpper() store-items" data-price="@item.Price.ToString("F2")" data-name=".@item.Name.Replace(" ", string.Empty).ToUpper()">
                <div class="card m-2">
                    <img class="card-img-top" src="@item.Image" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title text-center font-weight-bold">@item.Name.ToUpper()</h5>
                        <p class="card-text badge badge-primary text-left">@item.SubCategory.Name</p>
                        <h5 class="card-text price font-weight-bold text-success">@item.Price.ToString("C2")</h5>
                        <p class="card-text text-justify">@item.Description</p>
                    </div>
                    <div class="card-footer text-center">
                        <a asp-action="Details" class="btn btn-lg btn-success font-weight-bold" asp-route-id="@item.Id">COMPRAR</a>
                    </div>
                </div>
            </div>
        }

    </div>

}